version: '2.3'

services:
    python:
        build:
            context: .
            dockerfile: docker/python/Dockerfile
        runtime: nvidia
        environment:
            - NVIDIA_VISIBLE_DEVICES=all
            - NVIDIA_DRIVER_CAPABILITIES=all
            - H2O_APP_ADDRESS=http://wave_server:8000
            - H2O_WAVE_ADDRESS=http://wave_server:10101
        volumes:
            - .:/usr/src
            - /mnt/D/Data/animefacedataset:/usr/src/data/animefacedataset
            - /mnt/D/Data/tagged-anime-illustrations:/usr/src/data/danbooru
            - /mnt/D/Data/illustration2vec:/usr/src/data/illustration2vec
        working_dir: /usr/src
        tty: true
        shm_size: '2gb'
        depends_on:
            - wave_server

    wave_server:
        build:
            context: .
            dockerfile: docker/wave/Dockerfile
            args:
                - WAVE_VERSION=0.10.0
        working_dir: /usr/wave
        command: ./waved
        ports:
            - '10101:10101'